import Head from "next/head";
import Image from "next/image";
import Button from "../components/button";
import HomepageHeader from "../components/HomepageHeader";
import Information from "../components/Information"
import Menu from "../components/Menu";
import Specialisations from "../components/Specialisations";
import Team from "../components/Teampage";
import { getPage } from '../lib/query/page';


const Home = () => {
  return (
    <div>
      <Head>
        <title>Diamond Fysio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Menu/>

        <HomepageHeader />
        <Specialisations />
        <Information/>
        <Team/>
      <footer></footer>
    </div>
  );
};

export default Home;

export const getStaticProps = async ({ preview = false }) => {
  const pageData = (await res.json);
  // const {
  //   navigation: {
  //     pagesCollection: { items: navigationItems },
  //   },
  // } = await getNavigation('3LwHjFAqWiIr3Mk66S1dwN');
  // const {
  //   footer: {
  //     navigationColumnsCollection: { items: footerItems },
  //     facebook,
  //     linkedIn,
  //     youtube,
  //   },
  // } = await getFooter('5r5ybGKJOX0rTBNC5Ef9Q1');

  return {
    props: {
      ...pageData,
      // navigationItems: navigationItems,
      // footer: {
      //   footerItems: footerItems,
      //   socials: { facebook: facebook, linkedin: linkedIn, youtube: youtube },
      // },
      // preview: preview,
    },
  };
};