import Head from "next/head";
import Image from "next/image";
import Button from "../components/button";
import HomepageHeader from "../components/HomepageHeader";
import Information from "../components/Information"
import Menu from "../components/Menu";
import Specialisations from "../components/Specialisations";
import Team from "../components/Teampage";
import {getClient } from "../lib/contentful";
import { createClient } from "contentful";

export async function getStaticProps() {
  const res = await getClient.getTeamMembers( { content_type: 'teamMember' } )
  return {
    props: {
      teamMembers: res.items
    }
  }
}



const Home = ( {teamMembers} ) => {
  console.log('test', teamMembers)
  return (
    <div>
      <Head>
        <title>Diamond Fysio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Menu/>

        <HomepageHeader />
        <Specialisations />
        <Information/>
        <Team/>
      <footer></footer>
    </div>
  );
};

export default Home;
