import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Information from "../components/Information"
import Menu from "../components/Menu";
import Specialisations from "../components/Specialisations";
import { createClient } from "contentful";
import Homepage from "../components/Homepage"

export async function getStaticProps() {

  const client = createClient({
    space: process.env.REACT_APP_CONTENTFUL_SPACE_ID,
    accessToken: process.env.REACT_APP_CONTENTFUL_ACCESS_TOKEN
  })
  const res = await client.getEntries( { content_type: 'teamMember' } )
  console.log('res', res)
  return {
    props: {
      teamMembers: res.items
    }
  }
}



const Home = ( ) => {
  return (
    <div>
      <Head>
        <title>Diamond Fysio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Menu/>

        <Header />
        <Specialisations />
        <Information/>
      <footer></footer>
    </div>
  );
};

export default Home;
