import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Information from "../components/Information"
import Menu from "../components/Menu";
import Specialisations from "../components/Specialisations";
import { createClient } from "contentful";

export async function getStaticProps() {
  console.log('hi', process.env)

  const space = "vmz4lv5fgrcj"
  const accessToken = "2BXxL6w674uw8WYJagRluKrqpB_kSL2hP3czCI1LA64"
  console.log('jhi', space)
  const client = createClient({
    space: space, 
    accessToken: accessToken,
  })
  const res = await client.getEntries( { content_type: 'teamMember' } )
  console.log('res', res)
  return {
    props: {
      teamMembers: res.items
    }
  }
}



const Home = ( ) => {
  return (
    <div>
      <Head>
        <title>Diamond Fysio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Menu/>

        <Header />
        <Specialisations />
        <Information/>
      <footer></footer>
    </div>
  );
};

export default Home;
