import Head from "next/head";
import Image from "next/image";
import Button from "../components/button";

const Home = ({}) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <Button text="test" type="primary" />
        <Button text="test" type="primary" negative />
        <Button text="test" type="primary" small />
        <Button text="test" type="primary" small negative />
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
